<a href="https://colab.research.google.com/github/Uzma-Jawed/python-class_work-and-practice/blob/main/DataAnalysisWithPandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 📘 Importing Required Library & Dataset

In [ ]:
import pandas as pd

In [ ]:
# Load dataset
data = pd.read_csv('/content/sample_data/california_housing_train.csv')

In [ ]:
# Display entire dataframe (optional: usually shows full data in Colab)
data

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0
...,...,...,...,...,...,...,...,...,...
16995,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0
16997,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0

In [ ]:
# First Rows
data.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0

In [ ]:
# Last Rows
data.tail()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
16995,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0
16997,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0

In [ ]:
# Shape of the data (rows, columns)
data.shape

(17000, 9)

In [ ]:
# Info about column types and null values
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17000 entries, 0 to 16999
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           17000 non-null  float64
 1   latitude            17000 non-null  float64
 2   housing_median_age  17000 non-null  float64
 3   total_rooms         17000 non-null  float64
 4   total_bedrooms      17000 non-null  float64
 5   population          17000 non-null  float64
 6   households          17000 non-null  float64
 7   median_income       17000 non-null  float64
 8   median_house_value  17000 non-null  float64
dtypes: float64(9)
memory usage: 1.2 MB

In [ ]:
# Summary statistics
data.describe()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
count,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000
mean,-119.562108,35.625225,28.589353,2643.664412,539.410824,1429.573941,501.221941,3.883578,207300.912353
std,2.005166,2.137340,12.586937,2179.947071,421.499452,1147.852959,384.520841,1.908157,115983.764387
min,-124.350000,32.540000,1.000000,2.000000,1.000000,3.000000,1.000000,0.499900,14999.000000
25%,-121.790000,33.930000,18.000000,1462.000000,297.000000,790.000000,282.000000,2.566375,119400.000000
50%,-118.490000,34.250000,29.000000,2127.000000,434.000000,1167.000000,409.000000,3.544600,180400.000000
75%,-118.000000,37.720000,37.000000,3151.250000,648.250000,1721.000000,605.250000,4.767000,265000.000000
max,-114.310000,41.950000,52.000000,37937.000000,6445.000000,35682.000000,6082.000000,15.000100,500001.000000

📊 Introduction to Statistics in Data Analysis

In data science, statistics helps summarize, describe, and draw conclusions from data.

📂 Types of Data
1. Quantitative Data
Numerical data (e.g., income, age, population).

2. Qualitative Data
Categorical or descriptive data (e.g., gender, city). Not present in this dataset.

3. Descriptive Statistics
Summarizes features of a dataset using:

Mean, Median, Mode

Range, Variance, Standard Deviation

4. Inferential Statistics

Uses sample data to make predictions or test hypotheses about a population.

5. Time Series Data

Data collected over time intervals (e.g., monthly sales).

📌 Measures of Central Tendency

These are used to identify the center or average of a data distribution.

| Measure    | Description              | Example     |
| ---------- | ------------------------ | ----------- |
| **Mean**   | Arithmetic average       | `.mean()`   |
| **Median** | Middle value when sorted | `.median()` |
| **Mode**   | Most frequent value      | `.mode()`   |

🔹 Median (Odd Count): Middle value

🔹 Median (Even Count): Average of two middle values

📐 Measures of Dispersion

Used to understand data spread and variability.

🔸 1. Range
Formula: max - min

🔸 2. Variance
Average of squared deviations from the mean

🔸 3. Standard Deviation (SD)
Square root of variance

Measures spread around the mean

🔸 4. Interquartile Range (IQR)
IQR = Q3 - Q1

Helps detect outliers

📈 Quartiles and Quartile Deviation

| Quartile | Description            |
| -------- | ---------------------- |
| **Q1**   | 25% of data below this |
| **Q2**   | 50% (Median)           |
| **Q3**   | 75% of data below this |

Quartile Deviation (QD)


QD = (Q3 - Q1) / 2

Coefficient of QD

(Q3 - Q1) / (Q3 + Q1) → A relative (unit-less) measure

🔍 Outlier Detection (Using IQR)

Lower bound: Q1 - 1.5 × IQR

Upper bound: Q3 + 1.5 × IQR

Any value outside this range is an outlier

| Measure Type | Description | Example                         |
| ------------ | ----------- | ------------------------------- |
| **Absolute** | Has units   | Range in dollars                |
| **Relative** | No units    | Ratio, Coefficient of Variation |

🧪 Hypothesis Testing

Part of inferential statistics

Used to test assumptions using sample data

In [ ]:
# get data of a particular column
data['housing_median_age']

0        15.0
1        19.0
2        17.0
3        14.0
4        20.0
         ...
16995    52.0
16996    36.0
16997    17.0
16998    19.0
16999    52.0
Name: housing_median_age, Length: 17000, dtype: float64



---

📐 Measures of Central Tendency



Mean: Average value (e.g., business revenue)


Median: Midpoint of data when sorted


Mode: Most frequent value in dataset

In [ ]:
# Mean
data.mean()

longitude               -119.562108
latitude                  35.625225
housing_median_age        28.589353
total_rooms             2643.664412
total_bedrooms           539.410824
population              1429.573941
households               501.221941
median_income              3.883578
median_house_value    207300.912353
dtype: float64

In [ ]:
# Median
data.median()

longitude               -118.4900
latitude                  34.2500
housing_median_age        29.0000
total_rooms             2127.0000
total_bedrooms           434.0000
population              1167.0000
households               409.0000
median_income              3.5446
median_house_value    180400.0000
dtype: float64

In [ ]:
# Mode
data.mode()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-118.31,34.06,52.0,1582.0,280.0,891.0,306.0,3.125,500001.0
1,NaN,NaN,NaN,NaN,NaN,NaN,386.0,NaN,NaN

In [ ]:
# Checking for outliers using IQR
data['housing_median_age'].quantile([0.25, 0.75])

0.25    18.0
0.75    37.0
Name: housing_median_age, dtype: float64



---

✅ Quartile Deviation Code

In [ ]:
# Interquartile Range (IQR) =  (Q3 - Q1)
IQR = 37.0 - 18.0

In [ ]:
IQR

19.0

In [ ]:
# Quartile Deviation (QD) = IQR/2
QD = 19.0 / 2

In [ ]:
QD

9.5

In [ ]:
# Coefficient of Quartile Deviation (QD) = (Q3 - Q1) / (Q3 + Q1)
coeff_QD = (37.0 - 18.0) / (37.0 + 18.0)

In [ ]:
coeff_QD

0.34545454545454546